<?php

include_once __DIR__."/../Controller/BookmarksController.php";
include_once __DIR__."/../Util/Util.php";
class Bookmarks extends BookmarksController
{
    private $data;
    private $clean;
    private $key;

    public function __construct()
    {
        parent::__construct();
        $this->clean = new Util();
        $this->data = isset($_POST) && count($_POST) > 0 ? parent::decode(parent::encode($_POST)) : parent::decode(file_get_contents("php://input"));

        $this->key = getenv("SECRET");
    }

    public function add(){
        $user_id = Util::tokenValidate();
        if($this->clean->Method() !== "POST" && !(array) $this->data || !$user_id)
            return array('status'=>403,'payload'=>"Unauthorized Access");

        $status = 403;
        $data = $this->data;

        $post = isset($data->post) ? $this->clean->clean_input($data->post) : '';

        $data = "Sorry something went wrong!";
        if(!empty($post) && !parent::exist($post, $user_id)){
            $sql = parent::addFavorite($this->encode(['post'=>$post, 'user'=>$user_id]));
            if($sql){
                $status = 200;
                $data = "Bookmark was added successful!";
            }
        }

        return array('status'=>$status, 'payload'=>$data);
    }

    public function remove(){
        $user_id = Util::tokenValidate();
        if($this->clean->Method() !== "POST")
            return array('status'=>403,'payload'=>"Unauthorized Access");

        $status = 403;
        $data = 'Unauthorized Access';
        if(!empty($user_id) && !empty($this->data->post)) {
            $sql = parent::deleteMark($this->data->post, $user_id);

            if($sql){
                $status = 200;
                $data = "";
            }
        }
        return array('status'=>$status, 'payload'=>$data);
    }

    public function get(){
        $user_id = Util::tokenValidate();
        if($this->clean->Method() !== "GET")
            return array('status'=>403,'payload'=>"Unauthorized Access");

        $status = 403;
        $data = 'Unauthorized Access';


        // controllers
        include_once __DIR__."/../Controller/PostController.php";
        include_once __DIR__."/../Controller/UsersController.php";
        include_once __DIR__."/../Controller/CategoriesController.php";

        if(!empty($user_id)) {
            $sql = parent::getFavorite($user_id); // TODO: Change the autogenerated stub

            if($sql){
                $status = 200;
                $data = [];
               $post = new PostController();

                foreach ($sql as $item) {
                   $pid = $item['post'];
                    $ps = $post->getPost($pid);

                    if($ps) {
                        $ps = $ps[0];
                        $status = 200;
                        $userd = new UsersController();

                        $cat = (new CategoriesController())->getLike($ps['category']);
                        $ps['category'] = $cat->name;
                        $user = ($userd->get($user_id));
                        $username = $user->username;
                        $avatar = $user->avatar;
                        $ps['user'] = $username;
                        $ps['avatar'] = $avatar;
                        $ps['description'] = nl2br($ps['description']);
                        $ps['created_at'] = Util::ago($ps['created_at']);
                        $ps['deadline'] = date("M, d Y", strtotime($ps['deadline']));
                        $ps['min_amount'] = (int) $ps['min_amount'];
                        $ps['max_amount'] = (int) $ps['max_amount'];
                        $total = Util::short_number($ps['max_amount'] + $ps['min_amount']) ;
                        $ps['total'] = $total;
                        $ps['featured'] = "public/uploads/$username/data/".$ps['featured'];
                        $m = explode(',',$ps['media']);
                        $md = '';
                        if(count($m) > 0){
                            for ($x = 0; $x <= count($m)-1; $x++) {
                                if($m[$x] !== '')
                                    $md .= "public/uploads/$username/data/".$m[$x].',';
                            }
                            $sql['media'] = chop($md,',');
                        }
                    }
                    $data[] = $ps;
               }
            }
        }

        return array('status'=>$status, 'payload'=>$data);
    }
}

$class = new Bookmarks();