<?php

include_once __DIR__."/../Module/CategoriesModule.php";

class CategoriesController extends CategoriesModule
{
    public function __construct()
    {
        parent::__construct();
    }

    public function addCategory($data)
    {
        return parent::addCategory($data); // TODO: Change the autogenerated stub
    }

    public function updateCategory($data)
    {
        return parent::updateCategory($data); // TODO: Change the autogenerated stub
    }

    public function get($id = '',$limit ='')
    {
        $data = parent::get($id,$limit); // TODO: Change the autogenerated stub
        if($data && $data->num_rows > 0){

            if(!empty($id))
                $data = $data->fetch_object();
            else
                $data = $data->fetch_all(MYSQLI_ASSOC);
        }

        return $data;
    }

    public function getLike($id = '')
    {
        $data = parent::get($id); // TODO: Change the autogenerated stub
        if($data && $data->num_rows > 0){

            if(!empty($id))
                $data = $data->fetch_object();
            else
                $data = $data->fetch_all(MYSQLI_ASSOC);
        }

        return $data;
    }

    public function exist($id)
    {
        $sql = parent::exist($id);
        return ($sql) && $sql->num_rows >0; // TODO: Change the autogenerated stub
    }
}